/*
Gurufocus Data Package API

API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ValuationsNNOREITNODIRECT type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValuationsNNOREITNODIRECT{}

// ValuationsNNOREITNODIRECT struct for ValuationsNNOREITNODIRECT
type ValuationsNNOREITNODIRECT struct {
	BasicInformation *ValuationsNNOREITNODIRECTBasicInformation `json:"basic_information,omitempty"`
	PerShareData *ValuationsNNOREITNODIRECTPerShareData `json:"per_share_data,omitempty"`
	Ratios *ValuationsNNOREITNODIRECTRatios `json:"ratios,omitempty"`
	ValuationRatios *ValuationsNNOREITNODIRECTValuationRatios `json:"valuation_ratios,omitempty"`
	ValuationandQuality *ValuationsNNOREITNODIRECTValuationandQuality `json:"valuationand_quality,omitempty"`
}

// NewValuationsNNOREITNODIRECT instantiates a new ValuationsNNOREITNODIRECT object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValuationsNNOREITNODIRECT() *ValuationsNNOREITNODIRECT {
	this := ValuationsNNOREITNODIRECT{}
	return &this
}

// NewValuationsNNOREITNODIRECTWithDefaults instantiates a new ValuationsNNOREITNODIRECT object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValuationsNNOREITNODIRECTWithDefaults() *ValuationsNNOREITNODIRECT {
	this := ValuationsNNOREITNODIRECT{}
	return &this
}

// GetBasicInformation returns the BasicInformation field value if set, zero value otherwise.
func (o *ValuationsNNOREITNODIRECT) GetBasicInformation() ValuationsNNOREITNODIRECTBasicInformation {
	if o == nil || IsNil(o.BasicInformation) {
		var ret ValuationsNNOREITNODIRECTBasicInformation
		return ret
	}
	return *o.BasicInformation
}

// GetBasicInformationOk returns a tuple with the BasicInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValuationsNNOREITNODIRECT) GetBasicInformationOk() (*ValuationsNNOREITNODIRECTBasicInformation, bool) {
	if o == nil || IsNil(o.BasicInformation) {
		return nil, false
	}
	return o.BasicInformation, true
}

// HasBasicInformation returns a boolean if a field has been set.
func (o *ValuationsNNOREITNODIRECT) HasBasicInformation() bool {
	if o != nil && !IsNil(o.BasicInformation) {
		return true
	}

	return false
}

// SetBasicInformation gets a reference to the given ValuationsNNOREITNODIRECTBasicInformation and assigns it to the BasicInformation field.
func (o *ValuationsNNOREITNODIRECT) SetBasicInformation(v ValuationsNNOREITNODIRECTBasicInformation) {
	o.BasicInformation = &v
}

// GetPerShareData returns the PerShareData field value if set, zero value otherwise.
func (o *ValuationsNNOREITNODIRECT) GetPerShareData() ValuationsNNOREITNODIRECTPerShareData {
	if o == nil || IsNil(o.PerShareData) {
		var ret ValuationsNNOREITNODIRECTPerShareData
		return ret
	}
	return *o.PerShareData
}

// GetPerShareDataOk returns a tuple with the PerShareData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValuationsNNOREITNODIRECT) GetPerShareDataOk() (*ValuationsNNOREITNODIRECTPerShareData, bool) {
	if o == nil || IsNil(o.PerShareData) {
		return nil, false
	}
	return o.PerShareData, true
}

// HasPerShareData returns a boolean if a field has been set.
func (o *ValuationsNNOREITNODIRECT) HasPerShareData() bool {
	if o != nil && !IsNil(o.PerShareData) {
		return true
	}

	return false
}

// SetPerShareData gets a reference to the given ValuationsNNOREITNODIRECTPerShareData and assigns it to the PerShareData field.
func (o *ValuationsNNOREITNODIRECT) SetPerShareData(v ValuationsNNOREITNODIRECTPerShareData) {
	o.PerShareData = &v
}

// GetRatios returns the Ratios field value if set, zero value otherwise.
func (o *ValuationsNNOREITNODIRECT) GetRatios() ValuationsNNOREITNODIRECTRatios {
	if o == nil || IsNil(o.Ratios) {
		var ret ValuationsNNOREITNODIRECTRatios
		return ret
	}
	return *o.Ratios
}

// GetRatiosOk returns a tuple with the Ratios field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValuationsNNOREITNODIRECT) GetRatiosOk() (*ValuationsNNOREITNODIRECTRatios, bool) {
	if o == nil || IsNil(o.Ratios) {
		return nil, false
	}
	return o.Ratios, true
}

// HasRatios returns a boolean if a field has been set.
func (o *ValuationsNNOREITNODIRECT) HasRatios() bool {
	if o != nil && !IsNil(o.Ratios) {
		return true
	}

	return false
}

// SetRatios gets a reference to the given ValuationsNNOREITNODIRECTRatios and assigns it to the Ratios field.
func (o *ValuationsNNOREITNODIRECT) SetRatios(v ValuationsNNOREITNODIRECTRatios) {
	o.Ratios = &v
}

// GetValuationRatios returns the ValuationRatios field value if set, zero value otherwise.
func (o *ValuationsNNOREITNODIRECT) GetValuationRatios() ValuationsNNOREITNODIRECTValuationRatios {
	if o == nil || IsNil(o.ValuationRatios) {
		var ret ValuationsNNOREITNODIRECTValuationRatios
		return ret
	}
	return *o.ValuationRatios
}

// GetValuationRatiosOk returns a tuple with the ValuationRatios field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValuationsNNOREITNODIRECT) GetValuationRatiosOk() (*ValuationsNNOREITNODIRECTValuationRatios, bool) {
	if o == nil || IsNil(o.ValuationRatios) {
		return nil, false
	}
	return o.ValuationRatios, true
}

// HasValuationRatios returns a boolean if a field has been set.
func (o *ValuationsNNOREITNODIRECT) HasValuationRatios() bool {
	if o != nil && !IsNil(o.ValuationRatios) {
		return true
	}

	return false
}

// SetValuationRatios gets a reference to the given ValuationsNNOREITNODIRECTValuationRatios and assigns it to the ValuationRatios field.
func (o *ValuationsNNOREITNODIRECT) SetValuationRatios(v ValuationsNNOREITNODIRECTValuationRatios) {
	o.ValuationRatios = &v
}

// GetValuationandQuality returns the ValuationandQuality field value if set, zero value otherwise.
func (o *ValuationsNNOREITNODIRECT) GetValuationandQuality() ValuationsNNOREITNODIRECTValuationandQuality {
	if o == nil || IsNil(o.ValuationandQuality) {
		var ret ValuationsNNOREITNODIRECTValuationandQuality
		return ret
	}
	return *o.ValuationandQuality
}

// GetValuationandQualityOk returns a tuple with the ValuationandQuality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValuationsNNOREITNODIRECT) GetValuationandQualityOk() (*ValuationsNNOREITNODIRECTValuationandQuality, bool) {
	if o == nil || IsNil(o.ValuationandQuality) {
		return nil, false
	}
	return o.ValuationandQuality, true
}

// HasValuationandQuality returns a boolean if a field has been set.
func (o *ValuationsNNOREITNODIRECT) HasValuationandQuality() bool {
	if o != nil && !IsNil(o.ValuationandQuality) {
		return true
	}

	return false
}

// SetValuationandQuality gets a reference to the given ValuationsNNOREITNODIRECTValuationandQuality and assigns it to the ValuationandQuality field.
func (o *ValuationsNNOREITNODIRECT) SetValuationandQuality(v ValuationsNNOREITNODIRECTValuationandQuality) {
	o.ValuationandQuality = &v
}

func (o ValuationsNNOREITNODIRECT) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValuationsNNOREITNODIRECT) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BasicInformation) {
		toSerialize["basic_information"] = o.BasicInformation
	}
	if !IsNil(o.PerShareData) {
		toSerialize["per_share_data"] = o.PerShareData
	}
	if !IsNil(o.Ratios) {
		toSerialize["ratios"] = o.Ratios
	}
	if !IsNil(o.ValuationRatios) {
		toSerialize["valuation_ratios"] = o.ValuationRatios
	}
	if !IsNil(o.ValuationandQuality) {
		toSerialize["valuationand_quality"] = o.ValuationandQuality
	}
	return toSerialize, nil
}

type NullableValuationsNNOREITNODIRECT struct {
	value *ValuationsNNOREITNODIRECT
	isSet bool
}

func (v NullableValuationsNNOREITNODIRECT) Get() *ValuationsNNOREITNODIRECT {
	return v.value
}

func (v *NullableValuationsNNOREITNODIRECT) Set(val *ValuationsNNOREITNODIRECT) {
	v.value = val
	v.isSet = true
}

func (v NullableValuationsNNOREITNODIRECT) IsSet() bool {
	return v.isSet
}

func (v *NullableValuationsNNOREITNODIRECT) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValuationsNNOREITNODIRECT(val *ValuationsNNOREITNODIRECT) *NullableValuationsNNOREITNODIRECT {
	return &NullableValuationsNNOREITNODIRECT{value: val, isSet: true}
}

func (v NullableValuationsNNOREITNODIRECT) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValuationsNNOREITNODIRECT) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


