/*
Gurufocus Data Package API

API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FundamentalsNNOREITNODIRECT type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FundamentalsNNOREITNODIRECT{}

// FundamentalsNNOREITNODIRECT struct for FundamentalsNNOREITNODIRECT
type FundamentalsNNOREITNODIRECT struct {
	BalanceSheet *FundamentalsNNOREITNODIRECTBalanceSheet `json:"balance_sheet,omitempty"`
	BasicInformation *FundamentalsNNOREITNODIRECTBasicInformation `json:"basic_information,omitempty"`
	CashflowStatement *FundamentalsNNOREITNODIRECTCashflowStatement `json:"cashflow_statement,omitempty"`
	IncomeStatement *FundamentalsNNOREITNODIRECTIncomeStatement `json:"income_statement,omitempty"`
}

// NewFundamentalsNNOREITNODIRECT instantiates a new FundamentalsNNOREITNODIRECT object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFundamentalsNNOREITNODIRECT() *FundamentalsNNOREITNODIRECT {
	this := FundamentalsNNOREITNODIRECT{}
	return &this
}

// NewFundamentalsNNOREITNODIRECTWithDefaults instantiates a new FundamentalsNNOREITNODIRECT object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFundamentalsNNOREITNODIRECTWithDefaults() *FundamentalsNNOREITNODIRECT {
	this := FundamentalsNNOREITNODIRECT{}
	return &this
}

// GetBalanceSheet returns the BalanceSheet field value if set, zero value otherwise.
func (o *FundamentalsNNOREITNODIRECT) GetBalanceSheet() FundamentalsNNOREITNODIRECTBalanceSheet {
	if o == nil || IsNil(o.BalanceSheet) {
		var ret FundamentalsNNOREITNODIRECTBalanceSheet
		return ret
	}
	return *o.BalanceSheet
}

// GetBalanceSheetOk returns a tuple with the BalanceSheet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsNNOREITNODIRECT) GetBalanceSheetOk() (*FundamentalsNNOREITNODIRECTBalanceSheet, bool) {
	if o == nil || IsNil(o.BalanceSheet) {
		return nil, false
	}
	return o.BalanceSheet, true
}

// HasBalanceSheet returns a boolean if a field has been set.
func (o *FundamentalsNNOREITNODIRECT) HasBalanceSheet() bool {
	if o != nil && !IsNil(o.BalanceSheet) {
		return true
	}

	return false
}

// SetBalanceSheet gets a reference to the given FundamentalsNNOREITNODIRECTBalanceSheet and assigns it to the BalanceSheet field.
func (o *FundamentalsNNOREITNODIRECT) SetBalanceSheet(v FundamentalsNNOREITNODIRECTBalanceSheet) {
	o.BalanceSheet = &v
}

// GetBasicInformation returns the BasicInformation field value if set, zero value otherwise.
func (o *FundamentalsNNOREITNODIRECT) GetBasicInformation() FundamentalsNNOREITNODIRECTBasicInformation {
	if o == nil || IsNil(o.BasicInformation) {
		var ret FundamentalsNNOREITNODIRECTBasicInformation
		return ret
	}
	return *o.BasicInformation
}

// GetBasicInformationOk returns a tuple with the BasicInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsNNOREITNODIRECT) GetBasicInformationOk() (*FundamentalsNNOREITNODIRECTBasicInformation, bool) {
	if o == nil || IsNil(o.BasicInformation) {
		return nil, false
	}
	return o.BasicInformation, true
}

// HasBasicInformation returns a boolean if a field has been set.
func (o *FundamentalsNNOREITNODIRECT) HasBasicInformation() bool {
	if o != nil && !IsNil(o.BasicInformation) {
		return true
	}

	return false
}

// SetBasicInformation gets a reference to the given FundamentalsNNOREITNODIRECTBasicInformation and assigns it to the BasicInformation field.
func (o *FundamentalsNNOREITNODIRECT) SetBasicInformation(v FundamentalsNNOREITNODIRECTBasicInformation) {
	o.BasicInformation = &v
}

// GetCashflowStatement returns the CashflowStatement field value if set, zero value otherwise.
func (o *FundamentalsNNOREITNODIRECT) GetCashflowStatement() FundamentalsNNOREITNODIRECTCashflowStatement {
	if o == nil || IsNil(o.CashflowStatement) {
		var ret FundamentalsNNOREITNODIRECTCashflowStatement
		return ret
	}
	return *o.CashflowStatement
}

// GetCashflowStatementOk returns a tuple with the CashflowStatement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsNNOREITNODIRECT) GetCashflowStatementOk() (*FundamentalsNNOREITNODIRECTCashflowStatement, bool) {
	if o == nil || IsNil(o.CashflowStatement) {
		return nil, false
	}
	return o.CashflowStatement, true
}

// HasCashflowStatement returns a boolean if a field has been set.
func (o *FundamentalsNNOREITNODIRECT) HasCashflowStatement() bool {
	if o != nil && !IsNil(o.CashflowStatement) {
		return true
	}

	return false
}

// SetCashflowStatement gets a reference to the given FundamentalsNNOREITNODIRECTCashflowStatement and assigns it to the CashflowStatement field.
func (o *FundamentalsNNOREITNODIRECT) SetCashflowStatement(v FundamentalsNNOREITNODIRECTCashflowStatement) {
	o.CashflowStatement = &v
}

// GetIncomeStatement returns the IncomeStatement field value if set, zero value otherwise.
func (o *FundamentalsNNOREITNODIRECT) GetIncomeStatement() FundamentalsNNOREITNODIRECTIncomeStatement {
	if o == nil || IsNil(o.IncomeStatement) {
		var ret FundamentalsNNOREITNODIRECTIncomeStatement
		return ret
	}
	return *o.IncomeStatement
}

// GetIncomeStatementOk returns a tuple with the IncomeStatement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsNNOREITNODIRECT) GetIncomeStatementOk() (*FundamentalsNNOREITNODIRECTIncomeStatement, bool) {
	if o == nil || IsNil(o.IncomeStatement) {
		return nil, false
	}
	return o.IncomeStatement, true
}

// HasIncomeStatement returns a boolean if a field has been set.
func (o *FundamentalsNNOREITNODIRECT) HasIncomeStatement() bool {
	if o != nil && !IsNil(o.IncomeStatement) {
		return true
	}

	return false
}

// SetIncomeStatement gets a reference to the given FundamentalsNNOREITNODIRECTIncomeStatement and assigns it to the IncomeStatement field.
func (o *FundamentalsNNOREITNODIRECT) SetIncomeStatement(v FundamentalsNNOREITNODIRECTIncomeStatement) {
	o.IncomeStatement = &v
}

func (o FundamentalsNNOREITNODIRECT) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FundamentalsNNOREITNODIRECT) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BalanceSheet) {
		toSerialize["balance_sheet"] = o.BalanceSheet
	}
	if !IsNil(o.BasicInformation) {
		toSerialize["basic_information"] = o.BasicInformation
	}
	if !IsNil(o.CashflowStatement) {
		toSerialize["cashflow_statement"] = o.CashflowStatement
	}
	if !IsNil(o.IncomeStatement) {
		toSerialize["income_statement"] = o.IncomeStatement
	}
	return toSerialize, nil
}

type NullableFundamentalsNNOREITNODIRECT struct {
	value *FundamentalsNNOREITNODIRECT
	isSet bool
}

func (v NullableFundamentalsNNOREITNODIRECT) Get() *FundamentalsNNOREITNODIRECT {
	return v.value
}

func (v *NullableFundamentalsNNOREITNODIRECT) Set(val *FundamentalsNNOREITNODIRECT) {
	v.value = val
	v.isSet = true
}

func (v NullableFundamentalsNNOREITNODIRECT) IsSet() bool {
	return v.isSet
}

func (v *NullableFundamentalsNNOREITNODIRECT) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFundamentalsNNOREITNODIRECT(val *FundamentalsNNOREITNODIRECT) *NullableFundamentalsNNOREITNODIRECT {
	return &NullableFundamentalsNNOREITNODIRECT{value: val, isSet: true}
}

func (v NullableFundamentalsNNOREITNODIRECT) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFundamentalsNNOREITNODIRECT) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


