/*
Gurufocus Data Package API

API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FundamentalsINOREITNODIRECT type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FundamentalsINOREITNODIRECT{}

// FundamentalsINOREITNODIRECT struct for FundamentalsINOREITNODIRECT
type FundamentalsINOREITNODIRECT struct {
	BalanceSheet *FundamentalsINOREITNODIRECTBalanceSheet `json:"balance_sheet,omitempty"`
	BasicInformation *FundamentalsINOREITNODIRECTBasicInformation `json:"basic_information,omitempty"`
	CashflowStatement *FundamentalsINOREITNODIRECTCashflowStatement `json:"cashflow_statement,omitempty"`
	IncomeStatement *FundamentalsINOREITNODIRECTIncomeStatement `json:"income_statement,omitempty"`
}

// NewFundamentalsINOREITNODIRECT instantiates a new FundamentalsINOREITNODIRECT object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFundamentalsINOREITNODIRECT() *FundamentalsINOREITNODIRECT {
	this := FundamentalsINOREITNODIRECT{}
	return &this
}

// NewFundamentalsINOREITNODIRECTWithDefaults instantiates a new FundamentalsINOREITNODIRECT object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFundamentalsINOREITNODIRECTWithDefaults() *FundamentalsINOREITNODIRECT {
	this := FundamentalsINOREITNODIRECT{}
	return &this
}

// GetBalanceSheet returns the BalanceSheet field value if set, zero value otherwise.
func (o *FundamentalsINOREITNODIRECT) GetBalanceSheet() FundamentalsINOREITNODIRECTBalanceSheet {
	if o == nil || IsNil(o.BalanceSheet) {
		var ret FundamentalsINOREITNODIRECTBalanceSheet
		return ret
	}
	return *o.BalanceSheet
}

// GetBalanceSheetOk returns a tuple with the BalanceSheet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsINOREITNODIRECT) GetBalanceSheetOk() (*FundamentalsINOREITNODIRECTBalanceSheet, bool) {
	if o == nil || IsNil(o.BalanceSheet) {
		return nil, false
	}
	return o.BalanceSheet, true
}

// HasBalanceSheet returns a boolean if a field has been set.
func (o *FundamentalsINOREITNODIRECT) HasBalanceSheet() bool {
	if o != nil && !IsNil(o.BalanceSheet) {
		return true
	}

	return false
}

// SetBalanceSheet gets a reference to the given FundamentalsINOREITNODIRECTBalanceSheet and assigns it to the BalanceSheet field.
func (o *FundamentalsINOREITNODIRECT) SetBalanceSheet(v FundamentalsINOREITNODIRECTBalanceSheet) {
	o.BalanceSheet = &v
}

// GetBasicInformation returns the BasicInformation field value if set, zero value otherwise.
func (o *FundamentalsINOREITNODIRECT) GetBasicInformation() FundamentalsINOREITNODIRECTBasicInformation {
	if o == nil || IsNil(o.BasicInformation) {
		var ret FundamentalsINOREITNODIRECTBasicInformation
		return ret
	}
	return *o.BasicInformation
}

// GetBasicInformationOk returns a tuple with the BasicInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsINOREITNODIRECT) GetBasicInformationOk() (*FundamentalsINOREITNODIRECTBasicInformation, bool) {
	if o == nil || IsNil(o.BasicInformation) {
		return nil, false
	}
	return o.BasicInformation, true
}

// HasBasicInformation returns a boolean if a field has been set.
func (o *FundamentalsINOREITNODIRECT) HasBasicInformation() bool {
	if o != nil && !IsNil(o.BasicInformation) {
		return true
	}

	return false
}

// SetBasicInformation gets a reference to the given FundamentalsINOREITNODIRECTBasicInformation and assigns it to the BasicInformation field.
func (o *FundamentalsINOREITNODIRECT) SetBasicInformation(v FundamentalsINOREITNODIRECTBasicInformation) {
	o.BasicInformation = &v
}

// GetCashflowStatement returns the CashflowStatement field value if set, zero value otherwise.
func (o *FundamentalsINOREITNODIRECT) GetCashflowStatement() FundamentalsINOREITNODIRECTCashflowStatement {
	if o == nil || IsNil(o.CashflowStatement) {
		var ret FundamentalsINOREITNODIRECTCashflowStatement
		return ret
	}
	return *o.CashflowStatement
}

// GetCashflowStatementOk returns a tuple with the CashflowStatement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsINOREITNODIRECT) GetCashflowStatementOk() (*FundamentalsINOREITNODIRECTCashflowStatement, bool) {
	if o == nil || IsNil(o.CashflowStatement) {
		return nil, false
	}
	return o.CashflowStatement, true
}

// HasCashflowStatement returns a boolean if a field has been set.
func (o *FundamentalsINOREITNODIRECT) HasCashflowStatement() bool {
	if o != nil && !IsNil(o.CashflowStatement) {
		return true
	}

	return false
}

// SetCashflowStatement gets a reference to the given FundamentalsINOREITNODIRECTCashflowStatement and assigns it to the CashflowStatement field.
func (o *FundamentalsINOREITNODIRECT) SetCashflowStatement(v FundamentalsINOREITNODIRECTCashflowStatement) {
	o.CashflowStatement = &v
}

// GetIncomeStatement returns the IncomeStatement field value if set, zero value otherwise.
func (o *FundamentalsINOREITNODIRECT) GetIncomeStatement() FundamentalsINOREITNODIRECTIncomeStatement {
	if o == nil || IsNil(o.IncomeStatement) {
		var ret FundamentalsINOREITNODIRECTIncomeStatement
		return ret
	}
	return *o.IncomeStatement
}

// GetIncomeStatementOk returns a tuple with the IncomeStatement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsINOREITNODIRECT) GetIncomeStatementOk() (*FundamentalsINOREITNODIRECTIncomeStatement, bool) {
	if o == nil || IsNil(o.IncomeStatement) {
		return nil, false
	}
	return o.IncomeStatement, true
}

// HasIncomeStatement returns a boolean if a field has been set.
func (o *FundamentalsINOREITNODIRECT) HasIncomeStatement() bool {
	if o != nil && !IsNil(o.IncomeStatement) {
		return true
	}

	return false
}

// SetIncomeStatement gets a reference to the given FundamentalsINOREITNODIRECTIncomeStatement and assigns it to the IncomeStatement field.
func (o *FundamentalsINOREITNODIRECT) SetIncomeStatement(v FundamentalsINOREITNODIRECTIncomeStatement) {
	o.IncomeStatement = &v
}

func (o FundamentalsINOREITNODIRECT) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FundamentalsINOREITNODIRECT) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BalanceSheet) {
		toSerialize["balance_sheet"] = o.BalanceSheet
	}
	if !IsNil(o.BasicInformation) {
		toSerialize["basic_information"] = o.BasicInformation
	}
	if !IsNil(o.CashflowStatement) {
		toSerialize["cashflow_statement"] = o.CashflowStatement
	}
	if !IsNil(o.IncomeStatement) {
		toSerialize["income_statement"] = o.IncomeStatement
	}
	return toSerialize, nil
}

type NullableFundamentalsINOREITNODIRECT struct {
	value *FundamentalsINOREITNODIRECT
	isSet bool
}

func (v NullableFundamentalsINOREITNODIRECT) Get() *FundamentalsINOREITNODIRECT {
	return v.value
}

func (v *NullableFundamentalsINOREITNODIRECT) Set(val *FundamentalsINOREITNODIRECT) {
	v.value = val
	v.isSet = true
}

func (v NullableFundamentalsINOREITNODIRECT) IsSet() bool {
	return v.isSet
}

func (v *NullableFundamentalsINOREITNODIRECT) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFundamentalsINOREITNODIRECT(val *FundamentalsINOREITNODIRECT) *NullableFundamentalsINOREITNODIRECT {
	return &NullableFundamentalsINOREITNODIRECT{value: val, isSet: true}
}

func (v NullableFundamentalsINOREITNODIRECT) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFundamentalsINOREITNODIRECT) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


