/*
Gurufocus Data Package API

API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the StocksSymbolValuationsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StocksSymbolValuationsGet200Response{}

// StocksSymbolValuationsGet200Response struct for StocksSymbolValuationsGet200Response
type StocksSymbolValuationsGet200Response struct {
	Annually []StockValuationsAnnuallyInner `json:"annually,omitempty"`
	BasicInformation *StockValuationsBasicInformation `json:"basic_information,omitempty"`
	Quarterly []StockValuationsAnnuallyInner `json:"quarterly,omitempty"`
	Ttm *StockValuationsTtm `json:"ttm,omitempty"`
}

// NewStocksSymbolValuationsGet200Response instantiates a new StocksSymbolValuationsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStocksSymbolValuationsGet200Response() *StocksSymbolValuationsGet200Response {
	this := StocksSymbolValuationsGet200Response{}
	return &this
}

// NewStocksSymbolValuationsGet200ResponseWithDefaults instantiates a new StocksSymbolValuationsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStocksSymbolValuationsGet200ResponseWithDefaults() *StocksSymbolValuationsGet200Response {
	this := StocksSymbolValuationsGet200Response{}
	return &this
}

// GetAnnually returns the Annually field value if set, zero value otherwise.
func (o *StocksSymbolValuationsGet200Response) GetAnnually() []StockValuationsAnnuallyInner {
	if o == nil || IsNil(o.Annually) {
		var ret []StockValuationsAnnuallyInner
		return ret
	}
	return o.Annually
}

// GetAnnuallyOk returns a tuple with the Annually field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StocksSymbolValuationsGet200Response) GetAnnuallyOk() ([]StockValuationsAnnuallyInner, bool) {
	if o == nil || IsNil(o.Annually) {
		return nil, false
	}
	return o.Annually, true
}

// HasAnnually returns a boolean if a field has been set.
func (o *StocksSymbolValuationsGet200Response) HasAnnually() bool {
	if o != nil && !IsNil(o.Annually) {
		return true
	}

	return false
}

// SetAnnually gets a reference to the given []StockValuationsAnnuallyInner and assigns it to the Annually field.
func (o *StocksSymbolValuationsGet200Response) SetAnnually(v []StockValuationsAnnuallyInner) {
	o.Annually = v
}

// GetBasicInformation returns the BasicInformation field value if set, zero value otherwise.
func (o *StocksSymbolValuationsGet200Response) GetBasicInformation() StockValuationsBasicInformation {
	if o == nil || IsNil(o.BasicInformation) {
		var ret StockValuationsBasicInformation
		return ret
	}
	return *o.BasicInformation
}

// GetBasicInformationOk returns a tuple with the BasicInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StocksSymbolValuationsGet200Response) GetBasicInformationOk() (*StockValuationsBasicInformation, bool) {
	if o == nil || IsNil(o.BasicInformation) {
		return nil, false
	}
	return o.BasicInformation, true
}

// HasBasicInformation returns a boolean if a field has been set.
func (o *StocksSymbolValuationsGet200Response) HasBasicInformation() bool {
	if o != nil && !IsNil(o.BasicInformation) {
		return true
	}

	return false
}

// SetBasicInformation gets a reference to the given StockValuationsBasicInformation and assigns it to the BasicInformation field.
func (o *StocksSymbolValuationsGet200Response) SetBasicInformation(v StockValuationsBasicInformation) {
	o.BasicInformation = &v
}

// GetQuarterly returns the Quarterly field value if set, zero value otherwise.
func (o *StocksSymbolValuationsGet200Response) GetQuarterly() []StockValuationsAnnuallyInner {
	if o == nil || IsNil(o.Quarterly) {
		var ret []StockValuationsAnnuallyInner
		return ret
	}
	return o.Quarterly
}

// GetQuarterlyOk returns a tuple with the Quarterly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StocksSymbolValuationsGet200Response) GetQuarterlyOk() ([]StockValuationsAnnuallyInner, bool) {
	if o == nil || IsNil(o.Quarterly) {
		return nil, false
	}
	return o.Quarterly, true
}

// HasQuarterly returns a boolean if a field has been set.
func (o *StocksSymbolValuationsGet200Response) HasQuarterly() bool {
	if o != nil && !IsNil(o.Quarterly) {
		return true
	}

	return false
}

// SetQuarterly gets a reference to the given []StockValuationsAnnuallyInner and assigns it to the Quarterly field.
func (o *StocksSymbolValuationsGet200Response) SetQuarterly(v []StockValuationsAnnuallyInner) {
	o.Quarterly = v
}

// GetTtm returns the Ttm field value if set, zero value otherwise.
func (o *StocksSymbolValuationsGet200Response) GetTtm() StockValuationsTtm {
	if o == nil || IsNil(o.Ttm) {
		var ret StockValuationsTtm
		return ret
	}
	return *o.Ttm
}

// GetTtmOk returns a tuple with the Ttm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StocksSymbolValuationsGet200Response) GetTtmOk() (*StockValuationsTtm, bool) {
	if o == nil || IsNil(o.Ttm) {
		return nil, false
	}
	return o.Ttm, true
}

// HasTtm returns a boolean if a field has been set.
func (o *StocksSymbolValuationsGet200Response) HasTtm() bool {
	if o != nil && !IsNil(o.Ttm) {
		return true
	}

	return false
}

// SetTtm gets a reference to the given StockValuationsTtm and assigns it to the Ttm field.
func (o *StocksSymbolValuationsGet200Response) SetTtm(v StockValuationsTtm) {
	o.Ttm = &v
}

func (o StocksSymbolValuationsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StocksSymbolValuationsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Annually) {
		toSerialize["annually"] = o.Annually
	}
	if !IsNil(o.BasicInformation) {
		toSerialize["basic_information"] = o.BasicInformation
	}
	if !IsNil(o.Quarterly) {
		toSerialize["quarterly"] = o.Quarterly
	}
	if !IsNil(o.Ttm) {
		toSerialize["ttm"] = o.Ttm
	}
	return toSerialize, nil
}

type NullableStocksSymbolValuationsGet200Response struct {
	value *StocksSymbolValuationsGet200Response
	isSet bool
}

func (v NullableStocksSymbolValuationsGet200Response) Get() *StocksSymbolValuationsGet200Response {
	return v.value
}

func (v *NullableStocksSymbolValuationsGet200Response) Set(val *StocksSymbolValuationsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStocksSymbolValuationsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStocksSymbolValuationsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStocksSymbolValuationsGet200Response(val *StocksSymbolValuationsGet200Response) *NullableStocksSymbolValuationsGet200Response {
	return &NullableStocksSymbolValuationsGet200Response{value: val, isSet: true}
}

func (v NullableStocksSymbolValuationsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStocksSymbolValuationsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


