/*
Gurufocus Data Package API

API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DownloadListGet500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DownloadListGet500Response{}

// DownloadListGet500Response struct for DownloadListGet500Response
type DownloadListGet500Response struct {
	// Error code
	Code *float32 `json:"code,omitempty"`
	// Error message
	Message *string `json:"message,omitempty"`
}

// NewDownloadListGet500Response instantiates a new DownloadListGet500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDownloadListGet500Response() *DownloadListGet500Response {
	this := DownloadListGet500Response{}
	return &this
}

// NewDownloadListGet500ResponseWithDefaults instantiates a new DownloadListGet500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDownloadListGet500ResponseWithDefaults() *DownloadListGet500Response {
	this := DownloadListGet500Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *DownloadListGet500Response) GetCode() float32 {
	if o == nil || IsNil(o.Code) {
		var ret float32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadListGet500Response) GetCodeOk() (*float32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *DownloadListGet500Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given float32 and assigns it to the Code field.
func (o *DownloadListGet500Response) SetCode(v float32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DownloadListGet500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadListGet500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DownloadListGet500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DownloadListGet500Response) SetMessage(v string) {
	o.Message = &v
}

func (o DownloadListGet500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DownloadListGet500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDownloadListGet500Response struct {
	value *DownloadListGet500Response
	isSet bool
}

func (v NullableDownloadListGet500Response) Get() *DownloadListGet500Response {
	return v.value
}

func (v *NullableDownloadListGet500Response) Set(val *DownloadListGet500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDownloadListGet500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDownloadListGet500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDownloadListGet500Response(val *DownloadListGet500Response) *NullableDownloadListGet500Response {
	return &NullableDownloadListGet500Response{value: val, isSet: true}
}

func (v NullableDownloadListGet500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDownloadListGet500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


