/*
Gurufocus Data Package API

API for accessing Gurufocus data packages, please go to [https://www.gurufocus.com/user/me?tab=account&subtab=api-token](https://www.gurufocus.com/user/me?tab=account&subtab=api-token) to view or generate authorization keys.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FundamentalsIREITNODIRECT type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FundamentalsIREITNODIRECT{}

// FundamentalsIREITNODIRECT struct for FundamentalsIREITNODIRECT
type FundamentalsIREITNODIRECT struct {
	BalanceSheet *FundamentalsIREITNODIRECTBalanceSheet `json:"balance_sheet,omitempty"`
	BasicInformation *FundamentalsIREITNODIRECTBasicInformation `json:"basic_information,omitempty"`
	CashflowStatement *FundamentalsIREITNODIRECTCashflowStatement `json:"cashflow_statement,omitempty"`
	IncomeStatement *FundamentalsIREITNODIRECTIncomeStatement `json:"income_statement,omitempty"`
}

// NewFundamentalsIREITNODIRECT instantiates a new FundamentalsIREITNODIRECT object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFundamentalsIREITNODIRECT() *FundamentalsIREITNODIRECT {
	this := FundamentalsIREITNODIRECT{}
	return &this
}

// NewFundamentalsIREITNODIRECTWithDefaults instantiates a new FundamentalsIREITNODIRECT object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFundamentalsIREITNODIRECTWithDefaults() *FundamentalsIREITNODIRECT {
	this := FundamentalsIREITNODIRECT{}
	return &this
}

// GetBalanceSheet returns the BalanceSheet field value if set, zero value otherwise.
func (o *FundamentalsIREITNODIRECT) GetBalanceSheet() FundamentalsIREITNODIRECTBalanceSheet {
	if o == nil || IsNil(o.BalanceSheet) {
		var ret FundamentalsIREITNODIRECTBalanceSheet
		return ret
	}
	return *o.BalanceSheet
}

// GetBalanceSheetOk returns a tuple with the BalanceSheet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsIREITNODIRECT) GetBalanceSheetOk() (*FundamentalsIREITNODIRECTBalanceSheet, bool) {
	if o == nil || IsNil(o.BalanceSheet) {
		return nil, false
	}
	return o.BalanceSheet, true
}

// HasBalanceSheet returns a boolean if a field has been set.
func (o *FundamentalsIREITNODIRECT) HasBalanceSheet() bool {
	if o != nil && !IsNil(o.BalanceSheet) {
		return true
	}

	return false
}

// SetBalanceSheet gets a reference to the given FundamentalsIREITNODIRECTBalanceSheet and assigns it to the BalanceSheet field.
func (o *FundamentalsIREITNODIRECT) SetBalanceSheet(v FundamentalsIREITNODIRECTBalanceSheet) {
	o.BalanceSheet = &v
}

// GetBasicInformation returns the BasicInformation field value if set, zero value otherwise.
func (o *FundamentalsIREITNODIRECT) GetBasicInformation() FundamentalsIREITNODIRECTBasicInformation {
	if o == nil || IsNil(o.BasicInformation) {
		var ret FundamentalsIREITNODIRECTBasicInformation
		return ret
	}
	return *o.BasicInformation
}

// GetBasicInformationOk returns a tuple with the BasicInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsIREITNODIRECT) GetBasicInformationOk() (*FundamentalsIREITNODIRECTBasicInformation, bool) {
	if o == nil || IsNil(o.BasicInformation) {
		return nil, false
	}
	return o.BasicInformation, true
}

// HasBasicInformation returns a boolean if a field has been set.
func (o *FundamentalsIREITNODIRECT) HasBasicInformation() bool {
	if o != nil && !IsNil(o.BasicInformation) {
		return true
	}

	return false
}

// SetBasicInformation gets a reference to the given FundamentalsIREITNODIRECTBasicInformation and assigns it to the BasicInformation field.
func (o *FundamentalsIREITNODIRECT) SetBasicInformation(v FundamentalsIREITNODIRECTBasicInformation) {
	o.BasicInformation = &v
}

// GetCashflowStatement returns the CashflowStatement field value if set, zero value otherwise.
func (o *FundamentalsIREITNODIRECT) GetCashflowStatement() FundamentalsIREITNODIRECTCashflowStatement {
	if o == nil || IsNil(o.CashflowStatement) {
		var ret FundamentalsIREITNODIRECTCashflowStatement
		return ret
	}
	return *o.CashflowStatement
}

// GetCashflowStatementOk returns a tuple with the CashflowStatement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsIREITNODIRECT) GetCashflowStatementOk() (*FundamentalsIREITNODIRECTCashflowStatement, bool) {
	if o == nil || IsNil(o.CashflowStatement) {
		return nil, false
	}
	return o.CashflowStatement, true
}

// HasCashflowStatement returns a boolean if a field has been set.
func (o *FundamentalsIREITNODIRECT) HasCashflowStatement() bool {
	if o != nil && !IsNil(o.CashflowStatement) {
		return true
	}

	return false
}

// SetCashflowStatement gets a reference to the given FundamentalsIREITNODIRECTCashflowStatement and assigns it to the CashflowStatement field.
func (o *FundamentalsIREITNODIRECT) SetCashflowStatement(v FundamentalsIREITNODIRECTCashflowStatement) {
	o.CashflowStatement = &v
}

// GetIncomeStatement returns the IncomeStatement field value if set, zero value otherwise.
func (o *FundamentalsIREITNODIRECT) GetIncomeStatement() FundamentalsIREITNODIRECTIncomeStatement {
	if o == nil || IsNil(o.IncomeStatement) {
		var ret FundamentalsIREITNODIRECTIncomeStatement
		return ret
	}
	return *o.IncomeStatement
}

// GetIncomeStatementOk returns a tuple with the IncomeStatement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FundamentalsIREITNODIRECT) GetIncomeStatementOk() (*FundamentalsIREITNODIRECTIncomeStatement, bool) {
	if o == nil || IsNil(o.IncomeStatement) {
		return nil, false
	}
	return o.IncomeStatement, true
}

// HasIncomeStatement returns a boolean if a field has been set.
func (o *FundamentalsIREITNODIRECT) HasIncomeStatement() bool {
	if o != nil && !IsNil(o.IncomeStatement) {
		return true
	}

	return false
}

// SetIncomeStatement gets a reference to the given FundamentalsIREITNODIRECTIncomeStatement and assigns it to the IncomeStatement field.
func (o *FundamentalsIREITNODIRECT) SetIncomeStatement(v FundamentalsIREITNODIRECTIncomeStatement) {
	o.IncomeStatement = &v
}

func (o FundamentalsIREITNODIRECT) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FundamentalsIREITNODIRECT) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BalanceSheet) {
		toSerialize["balance_sheet"] = o.BalanceSheet
	}
	if !IsNil(o.BasicInformation) {
		toSerialize["basic_information"] = o.BasicInformation
	}
	if !IsNil(o.CashflowStatement) {
		toSerialize["cashflow_statement"] = o.CashflowStatement
	}
	if !IsNil(o.IncomeStatement) {
		toSerialize["income_statement"] = o.IncomeStatement
	}
	return toSerialize, nil
}

type NullableFundamentalsIREITNODIRECT struct {
	value *FundamentalsIREITNODIRECT
	isSet bool
}

func (v NullableFundamentalsIREITNODIRECT) Get() *FundamentalsIREITNODIRECT {
	return v.value
}

func (v *NullableFundamentalsIREITNODIRECT) Set(val *FundamentalsIREITNODIRECT) {
	v.value = val
	v.isSet = true
}

func (v NullableFundamentalsIREITNODIRECT) IsSet() bool {
	return v.isSet
}

func (v *NullableFundamentalsIREITNODIRECT) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFundamentalsIREITNODIRECT(val *FundamentalsIREITNODIRECT) *NullableFundamentalsIREITNODIRECT {
	return &NullableFundamentalsIREITNODIRECT{value: val, isSet: true}
}

func (v NullableFundamentalsIREITNODIRECT) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFundamentalsIREITNODIRECT) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


